/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category CloseInventory
 * @category generated
 */
public struct CloseInventoryInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = closeInventoryInstructionDiscriminator
    ) {
        self.instructionDiscriminator = instructionDiscriminator
    }
}
/**
 * @category Instructions
 * @category CloseInventory
 * @category generated
 */
public let closeInventoryStruct = FixableBeetArgsStruct<CloseInventoryInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        
    ],
    description: "CloseInventoryInstructionArgs"
)
/**
* Accounts required by the _closeInventory_ instruction
*
* @property [_writable_, **signer**] payer  
* @property [_writable_] inventory  
* @property [_writable_] assetInfo  
* @property [] mint   
* @category Instructions
* @category CloseInventory
* @category generated
*/
public struct CloseInventoryInstructionAccounts {
    let payer: PublicKey
    let inventory: PublicKey
    let assetInfo: PublicKey
    let mint: PublicKey
    let systemProgram: PublicKey?

    public init(
        payer: PublicKey,
        inventory: PublicKey,
        assetInfo: PublicKey,
        mint: PublicKey,
        systemProgram: PublicKey? = nil
    ) {
        self.payer = payer
        self.inventory = inventory
        self.assetInfo = assetInfo
        self.mint = mint
        self.systemProgram = systemProgram
    }
}

public let closeInventoryInstructionDiscriminator = [88, 141, 102, 160, 129, 133, 243, 233] as [UInt8]

/**
* Creates a _CloseInventory_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
* @category Instructions
* @category CloseInventory
* @category generated
*/
public func createCloseInventoryInstruction(accounts: CloseInventoryInstructionAccounts, 
programId: PublicKey=PublicKey(string: "8oRGerutEMGTumnzzgxbsCEfLLkghC3cdT6EadZaPh3Q")!) -> TransactionInstruction {

    let data = closeInventoryStruct.serialize(
            instance: ["instructionDiscriminator": closeInventoryInstructionDiscriminator ])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.inventory,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.assetInfo,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.mint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}