/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category CreateInventory
 * @category generated
 */
public struct CreateInventoryInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let price: UInt64

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = createInventoryInstructionDiscriminator,
        price: UInt64
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.price = price
    }
}
/**
 * @category Instructions
 * @category CreateInventory
 * @category generated
 */
public let createInventoryStruct = FixableBeetArgsStruct<CreateInventoryInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("price", Beet.fixedBeet(.init(value: .scalar(u64()))))
    ],
    description: "CreateInventoryInstructionArgs"
)
/**
* Accounts required by the _createInventory_ instruction
*
* @property [_writable_, **signer**] payer  
* @property [_writable_] inventory  
* @property [_writable_] assetInfo  
* @property [_writable_] usdcAccount  
* @property [] mint  
* @property [] usdcMint  
* @property [] associatedTokenProgram   
* @category Instructions
* @category CreateInventory
* @category generated
*/
public struct CreateInventoryInstructionAccounts {
    let payer: PublicKey
    let inventory: PublicKey
    let assetInfo: PublicKey
    let usdcAccount: PublicKey
    let mint: PublicKey
    let usdcMint: PublicKey
    let systemProgram: PublicKey?
    let tokenProgram: PublicKey?
    let associatedTokenProgram: PublicKey

    public init(
        payer: PublicKey,
        inventory: PublicKey,
        assetInfo: PublicKey,
        usdcAccount: PublicKey,
        mint: PublicKey,
        usdcMint: PublicKey,
        systemProgram: PublicKey? = nil,
        tokenProgram: PublicKey? = nil,
        associatedTokenProgram: PublicKey
    ) {
        self.payer = payer
        self.inventory = inventory
        self.assetInfo = assetInfo
        self.usdcAccount = usdcAccount
        self.mint = mint
        self.usdcMint = usdcMint
        self.systemProgram = systemProgram
        self.tokenProgram = tokenProgram
        self.associatedTokenProgram = associatedTokenProgram
    }
}

public let createInventoryInstructionDiscriminator = [199, 244, 185, 148, 32, 239, 38, 138] as [UInt8]

/**
* Creates a _CreateInventory_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category CreateInventory
* @category generated
*/
public func createCreateInventoryInstruction(accounts: CreateInventoryInstructionAccounts, 
args: CreateInventoryInstructionArgs, programId: PublicKey=PublicKey(string: "8oRGerutEMGTumnzzgxbsCEfLLkghC3cdT6EadZaPh3Q")!) -> TransactionInstruction {

    let data = createInventoryStruct.serialize(
            instance: ["instructionDiscriminator": createInventoryInstructionDiscriminator,
"price": args.price])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.inventory,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.assetInfo,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.usdcAccount,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.mint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.usdcMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.tokenProgram ?? PublicKey.tokenProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.associatedTokenProgram,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}