/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Solana
import Beet

/**
 * @category Instructions
 * @category WithdrawAsset
 * @category generated
 */
public struct WithdrawAssetInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = withdrawAssetInstructionDiscriminator
    ) {
        self.instructionDiscriminator = instructionDiscriminator
    }
}
/**
 * @category Instructions
 * @category WithdrawAsset
 * @category generated
 */
public let withdrawAssetStruct = FixableBeetArgsStruct<WithdrawAssetInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        
    ],
    description: "WithdrawAssetInstructionArgs"
)
/**
* Accounts required by the _withdrawAsset_ instruction
*
* @property [_writable_, **signer**] payer  
* @property [_writable_] inventory  
* @property [] mint   
* @category Instructions
* @category WithdrawAsset
* @category generated
*/
public struct WithdrawAssetInstructionAccounts {
    let payer: PublicKey
    let inventory: PublicKey
    let mint: PublicKey
    let systemProgram: PublicKey?

    public init(
        payer: PublicKey,
        inventory: PublicKey,
        mint: PublicKey,
        systemProgram: PublicKey? = nil
    ) {
        self.payer = payer
        self.inventory = inventory
        self.mint = mint
        self.systemProgram = systemProgram
    }
}

public let withdrawAssetInstructionDiscriminator = [78, 193, 207, 125, 63, 193, 129, 12] as [UInt8]

/**
* Creates a _WithdrawAsset_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
* @category Instructions
* @category WithdrawAsset
* @category generated
*/
public func createWithdrawAssetInstruction(accounts: WithdrawAssetInstructionAccounts, 
programId: PublicKey=PublicKey(string: "8oRGerutEMGTumnzzgxbsCEfLLkghC3cdT6EadZaPh3Q")!) -> TransactionInstruction {

    let data = withdrawAssetStruct.serialize(
            instance: ["instructionDiscriminator": withdrawAssetInstructionDiscriminator ])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.inventory,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.mint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}