/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import BeetSolana
import Solana
import Beet


/**
* Arguments used to create {@link Assetinfo}
* @category Accounts
* @category generated
*/
public protocol AssetinfoArgs {
    
     var assetKey: PublicKey { get }
     var price: UInt64 { get }
     var amount: UInt64 { get }
     var usdcRemitAccount: PublicKey { get }
}

/**
 * Holds the data for the {@link Assetinfo} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
public struct Assetinfo: AssetinfoArgs {
  

  public let assetKey: PublicKey
  public let price: UInt64
  public let amount: UInt64
  public let usdcRemitAccount: PublicKey

  /**
   * Creates a {@link Assetinfo} instance from the provided args.
   */
  public static func fromArgs(args: Args) -> Assetinfo {
    return Assetinfo(
        assetKey: args["assetKey"] as! PublicKey,
        price: args["price"] as! UInt64,
        amount: args["amount"] as! UInt64,
        usdcRemitAccount: args["usdcRemitAccount"] as! PublicKey
    )
  }
  /**
   * Deserializes the {@link Assetinfo} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func fromAccountInfo(
    accountInfo: Foundation.Data,
    offset:Int=0
  ) -> ( Assetinfo, Int )  {
    return Assetinfo.deserialize(buf: accountInfo, offset: offset)
  }
  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Assetinfo} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  public static func fromAccountAddress(
    connection: Api,
    address: PublicKey,
    onComplete: @escaping (Result<Assetinfo, Error>) -> Void
  ) {
    connection.getAccountInfo(account: address.base58EncodedString) { result in
        switch result {
            case .success(let pureData):
                if let data = pureData.data?.value {
                    onComplete(.success(Assetinfo.deserialize(buf: data).0))
                } else {
                    onComplete(.failure(SolanaError.nullValue))
                }
            case .failure(let error):
                onComplete(.failure(error))
        }
    }
  }
  /**
   * Deserializes the {@link Assetinfo} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func deserialize(
    buf: Foundation.Data,
    offset: Int = 0
  ) -> ( Assetinfo, Int ) {
    return assetInfoBeet.deserialize(buffer: buf, offset: offset)
  }
  /**
   * Serializes the {@link Assetinfo} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  public func serialize() -> ( Foundation.Data, Int ) {
    return assetInfoBeet.serialize(instance: Assetinfo(assetKey : self.assetKey,
        price : self.price,
        amount : self.amount,
        usdcRemitAccount : self.usdcRemitAccount))
  }
    /**
  * Returns the byteSize of a {@link Buffer} holding the serialized data of
  * {@link Assetinfo}
  */
  static func byteSize() -> UInt {
      return assetInfoBeet.byteSize
  }
  /**
  * Fetches the minimum balance needed to exempt an account holding
  * {@link Assetinfo} data from rent
  *
  * @param connection used to retrieve the rent exemption information
  */
  static func getMinimumBalanceForRentExemption(
      connection: Api,
      commitment: Commitment?,
      onComplete: @escaping(Result<UInt64, Error>) -> Void
  ) {
      return connection.getMinimumBalanceForRentExemption(dataLength: UInt64(Assetinfo.byteSize()), commitment: commitment, onComplete: onComplete)
  }
  /**
  * Determines if the provided {@link Buffer} has the correct byte size to
  * hold {@link Assetinfo} data.
  */
  static func hasCorrectByteSize(buf: Foundation.Data, offset:Int=0) -> Bool {
      return buf.bytes.count - offset == Assetinfo.byteSize()
  }
}
  /**
   * @category Accounts
   * @category generated
   */
  public let assetInfoBeet = BeetStruct(
    fields:[
        
        ("assetKey", (.init(value: .scalar(BeetPublicKey())))),
        ("price", (.init(value: .scalar(u64())))),
        ("amount", (.init(value: .scalar(u64())))),
        ("usdcRemitAccount", (.init(value: .scalar(BeetPublicKey()))))
    ],
    construct: Assetinfo.fromArgs,
    description: "Assetinfo"
)
